_target_: src.models.litho.img_mask.Mask
dataset_name: ibm_opc_test
layout_path: /home/local/eda13/gc29434/phd/projects/SMO-dev-dac24/data/ibm_opc_test/mask/t1_0_mask.png
target_path: /home/local/eda13/gc29434/phd/projects/SMO-dev-dac24/data/ibm_opc_test/mask/t1_0_mask.png
