_target_: src.betty.configs.EngineConfig
train_iters: ${eval:'${max_iters}*${problems.unroll_steps}'}
logger_type: aim
logger_repo: ${paths.log_dir}/${task_name}
valid_step: ${eval:'20*${problems.unroll_steps}'}
