defaults:
  - default

problem_type : cg
cg_iters: 3
unroll_steps: 4

mo:
  config:
    _target_: src.betty.configs.Config
    type: ${problems.problem_type}
    retain_graph: True
    log_step: 10
    cg_iterations: ${problems.cg_iters}
    cg_alpha: 1
    unroll_steps: ${problems.unroll_steps}

so:
  config:
    _target_: src.betty.configs.Config
    type: ${problems.problem_type}
    cg_iterations: ${problems.cg_iters}
    cg_alpha: 1
    unroll_steps: ${problems.unroll_steps}