_target_: src.models.moabbe_module.MOLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 20

# choose from cosine | sigmoid
mask_acti: sigmoid
mask_sigmoid_steepness: 4
mask_sigmoid_tr: 0.0

# parameters for lens in SMO model
lens_n_liquid: 1.414
lens_reduction: 0.25

target_intensity: 0.225

low_light_thres: 0.001

resist_sigmoid_steepness: 30
resist_sigmoid_tr: 0.225

weight_l2: 1000.0
weight_pvb: 0.001

save_img_folder: ${paths.data_dir}/moed
