# https://aimstack.io/

# example usage in lightning module:
# https://github.com/aimhubio/aim/blob/main/examples/pytorch_lightning_track.py

# open the Aim UI with the following command (run in the folder containing the `.aim` folder):
# `aim up`
# https://github.com/aimhubio/aim/blob/main/examples/pytorch_lightning_track.py

aim:
  _target_: aim.pytorch_lightning.AimLogger
  repo: ${paths.log_dir}/aim/
  system_tracking_interval: null
  log_system_params: False
  experiment: ${task_name}
  # enable/disable tracking console logs (default value is true)
  capture_terminal_logs: false # set to false to avoid infinite console log loop issue https://github.com/aimhubio/aim/issues/2550
