# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - source: abbe13.yaml
  - mask: img_mask.yaml
  - aerial: abbe.yaml
  - logger: aim.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

# Mask
task_name: "abbe"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["dev"]
