defaults:
  - _self_
  - source: iccad13
  - mask: img_mask
  - data: dummy
  - model: smo_iccad13
  - callbacks: iccad13
  - logger: aim
  - trainer: bilevel
  - paths: default
  - extras: default
  - hydra: default

  - experiment: null

  - hparams_search: null

  - optional local: default

  - debug: null
# Mask
task_name: "bilevel"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["dev"]

smo: True

ckpt_path: null

seed: null

inference: True
