# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - source: default
  - lens: default
  - tcc: default
  - mask: default
  - aerial: all # default
  - logger: null
  - paths: default
  - extras: default
  - hydra: default

# Mask
task_name: "litho"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["dev"]


# TCC
## 1. can be calculated
## 2. can be get form storage


