_target_: src.models.litho.abbe_litho.AbbeLitho
# resist_a: 100 # Resist model parameter: sharpness
# resist_t: 0.6 # Resist model parameter: threshold
# resist_tRef: 0.12 # combine with doselist, for resist image
# doseList:
#   - 1.0
# doseCoef:
#   - 1.0

# # for visualization
# vis:
#   aerial_show: false
#   aerial_save: false
#   aerial_save_path: ${paths.output_dir}/AI
#   resist_show: false
#   resist_save: false
#   resist_save_path: ${paths.output_dir}/RI

# parameters for lens in SMO model
# lens_n_liquid: 1.44
lens_n_liquid: 1.414
lens_reduction: 0.25
target_intensity: 0.225
